"""Integration tests for auto-mode full pipeline."""
from unittest.mock import MagicMock, patch
from pathlib import Path
from agent.state import AgentState


def _make_auto_state(output_dir: Path, auto_mode: bool = True) -> AgentState:
    """Helper to create a state for auto-mode testing."""
    return AgentState(
        raw_input="构建一个在线图书馆系统",
        auto_mode=auto_mode,
        requirements={
            "functional": ["借阅", "归还", "搜索"],
            "non_functional": ["并发 1000"],
            "actors": ["读者", "管理员"],
            "constraints": ["Web 应用"],
            "open_questions": [],
        },
        clarification_round=0,
        max_clarification_rounds=5,
        is_clear=True,
        clarify_questions=[],
        user_answers=[],
        req_doc_confirmed=False,
        high_level_confirmed=False,
        revision_comment=None,
        output_dir=output_dir,
        req_doc_path=None,
        high_level_doc_path=None,
        detail_doc_path=None,
        messages=[],
        errors=[],
        uml_diagram_files=[],
    )


@patch("agent.config.LLMClient")
def test_auto_mode_graph_runs_to_end(mock_llm_client_class, tmp_path):
    """Auto mode graph completes without checkpoints blocking the flow.

    The graph pipeline: process -> judge (fast-path) -> gen_req_doc
    -> high_level -> detail -> END.  Checkpoints are skipped due to auto_mode=True.
    """
    d = tmp_path / "outputs"
    d.mkdir(parents=True)

    from agent.graph import build_graph

    mock_client = MagicMock()
    # process parses JSON dict; gen_req_doc/high_level/detail write markdown
    mock_client.create_message.side_effect = [
        '{"functional": ["借阅", "归还", "搜索"], "non_functional": ["并发 1000"], "actors": ["读者", "管理员"], "constraints": ["Web 应用"], "open_questions": []}',
        "# Mocked 需求说明\n\nContent generated by mock.",
        "# Mocked 总体设计\n\nContent generated by mock.",
        '[]',  # extract_modules → 空列表，触发回退
        "# Mocked 详细设计\n\nContent created by mock.",
        '{"use-case.puml": "@startuml\n@enduml", "class-diagram.puml": "@startuml\n@enduml"}',
    ]
    mock_llm_client_class.return_value = mock_client

    graph = build_graph(use_memory=False)
    state = _make_auto_state(d, auto_mode=True)

    config = {"configurable": {"thread_id": "test-auto-1"}}
    final_state = None
    for s in graph.stream(state, config=config, stream_mode="values"):
        final_state = s

    assert final_state is not None
    assert final_state.get("req_doc_path") is not None
    assert final_state.get("high_level_doc_path") is not None
    assert final_state.get("detail_doc_path") is not None
    assert Path(final_state["req_doc_path"]).exists()
    assert Path(final_state["high_level_doc_path"]).exists()
    assert Path(final_state["detail_doc_path"]).exists()

    # Verify generated content
    req_content = Path(final_state["req_doc_path"]).read_text(encoding="utf-8")
    assert "Mocked 需求说明" in req_content

    # Verify gen_uml output
    assert len(final_state.get("uml_diagram_files", [])) == 2


@patch("agent.config.LLMClient")
def test_auto_mode_with_clarify_loop(mock_llm_client_class, tmp_path):
    """Auto mode completes even when judge sends it through clarify loop.

    The pipeline: process -> judge(LLM) -> clarify(auto) -> process(merge)
    -> judge(fast-path) -> gen_req_doc -> high_level -> detail -> END.
    """
    d = tmp_path / "outputs"
    d.mkdir(parents=True)

    from agent.graph import build_graph

    mock_client = MagicMock()
    # Call order:
    #   1. process (initial)   — returns reqs with open_questions
    #   2. judge (LLM)         — returns is_clear=False
    #   3. clarify (questions) — generates questions
    #   4. clarify (answers)   — auto-answers
    #   5. process (merged)    — returns reqs without open_questions
    #   6. gen_req_doc
    #   7. high_level
    #   8. detail
    mock_client.create_message.side_effect = [
        '{"functional": ["借阅", "归还"], "non_functional": [], "actors": ["读者"], "constraints": [], "open_questions": ["认证方式是什么？"]}',
        '{"is_clear": false}',
        '["认证方式是什么？"]',
        '["使用 JWT 认证"]',
        '{"functional": ["借阅", "归还", "认证"], "non_functional": [], "actors": ["读者"], "constraints": [], "open_questions": []}',
        "# 需求说明\n\nMock doc",
        "# 总体设计\n\nMock doc",
        '[]',  # extract_modules → 空列表，触发回退
        "# 详细设计\n\nMock doc",
        '{"use-case.puml": "@startuml\n@enduml"}',
    ]
    mock_llm_client_class.return_value = mock_client

    graph = build_graph(use_memory=False)
    state = _make_auto_state(d, auto_mode=True)
    state["is_clear"] = False
    state["requirements"]["open_questions"] = ["认证方式"]

    config = {"configurable": {"thread_id": "test-auto-2"}}
    final_state = None
    for s in graph.stream(state, config=config, stream_mode="values"):
        final_state = s

    assert final_state is not None
    assert final_state.get("req_doc_path") is not None
    assert final_state.get("high_level_doc_path") is not None
    assert final_state.get("detail_doc_path") is not None
    assert Path(final_state["req_doc_path"]).exists()
    assert Path(final_state["high_level_doc_path"]).exists()
    assert Path(final_state["detail_doc_path"]).exists()

    # Verify the clarify loop resolved open questions
    assert final_state["clarification_round"] == 1
    assert "认证方式" not in str(final_state.get("requirements", {}).get("open_questions", []))


@patch("agent.config.LLMClient")
def test_auto_mode_max_clarify_rounds(mock_llm_client_class, tmp_path):
    """Auto mode exits clarify loop when max rounds are reached.

    With max_clarification_rounds=1, the pipeline runs:
    process(0) -> judge(LLM,not clear) -> clarify(q+a) -> process(1)
    -> judge(LLM,not clear, but round=1>=max so route to ok)
    -> gen_req_doc -> high_level -> detail -> END.
    """
    d = tmp_path / "outputs"
    d.mkdir(parents=True)

    from agent.graph import build_graph

    mock_client = MagicMock()
    # Call order:
    #   1. process (initial)     — returns reqs with open_questions
    #   2. judge (LLM)           — not clear, routes to clarify
    #   3. clarify questions
    #   4. clarify answers       — round becomes 1
    #   5. process (with answers) — still returns open_questions
    #   6. judge (LLM)           — not clear, but round=1 >= max=1 routes to ok
    #   7. gen_req_doc
    #   8. high_level
    #   9. detail
    mock_client.create_message.side_effect = [
        '{"functional": ["借阅"], "non_functional": [], "actors": [], "constraints": [], "open_questions": ["still_unclear"]}',
        '{"is_clear": false}',
        '["What is the answer?"]',
        '["The answer is 42"]',
        '{"functional": ["借阅"], "non_functional": [], "actors": [], "constraints": [], "open_questions": ["still_unclear"]}',
        '{"is_clear": false}',
        "# 需求说明\n\nMock doc",
        "# 总体设计\n\nMock doc",
        '[]',  # extract_modules → 空列表，触发回退
        "# 详细设计\n\nMock doc",
        '{"use-case.puml": "@startuml\n@enduml"}',
    ]
    mock_llm_client_class.return_value = mock_client

    graph = build_graph(use_memory=False)
    state = _make_auto_state(d, auto_mode=True)
    state["is_clear"] = False
    state["requirements"]["open_questions"] = ["still_unclear"]
    state["max_clarification_rounds"] = 1

    config = {"configurable": {"thread_id": "test-auto-3"}}
    final_state = None
    for s in graph.stream(state, config=config, stream_mode="values"):
        final_state = s

    assert final_state is not None
    assert final_state.get("req_doc_path") is not None
    # Clarify loop ran exactly once, so round should be 1
    assert final_state["clarification_round"] == 1


def test_auto_mode_state_backward_compat():
    """When auto_mode not in state dict, .get() returns False."""
    state: AgentState = {
        "raw_input": "test",
        "requirements": {},
        "clarification_round": 0, "max_clarification_rounds": 5,
        "is_clear": False, "clarify_questions": [], "user_answers": [],
        "req_doc_confirmed": False, "high_level_confirmed": False,
        "revision_comment": None, "output_dir": Path("outputs/test"),
        "req_doc_path": None, "high_level_doc_path": None, "detail_doc_path": None,
        "messages": [], "errors": [],
    }
    # auto_mode key is absent — .get() should default to False
    assert state.get("auto_mode", False) is False


def test_auto_mode_flag_in_state():
    """When auto_mode is True, state reflects it."""
    state = _make_auto_state(Path("outputs/test"), auto_mode=True)
    assert state["auto_mode"] is True
    assert state.get("auto_mode", False) is True


def test_auto_mode_default_false():
    """When auto_mode is False, state reflects it correctly."""
    state = _make_auto_state(Path("outputs/test"), auto_mode=False)
    assert state["auto_mode"] is False
    assert state.get("auto_mode", False) is False
